# Generated by Django 5.0.1 on 2026-04-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_portal', '0005_add_resolved_at_to_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='civiccomplaint',
            name='latitude',
            field=models.DecimalField(decimal_places=15, help_text='Latitude coordinate (GPS)', max_digits=20),
        ),
        migrations.AlterField(
            model_name='civiccomplaint',
            name='longitude',
            field=models.DecimalField(decimal_places=15, help_text='Longitude coordinate (GPS)', max_digits=20),
        ),
    ]
