# Generated by Django 5.0.1 on 2026-04-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0002_remove_contractor_assigned_area_contractor_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketcompletion',
            name='contractor_latitude',
            field=models.DecimalField(decimal_places=15, help_text="Contractor's GPS latitude when uploading photo", max_digits=20),
        ),
        migrations.AlterField(
            model_name='ticketcompletion',
            name='contractor_longitude',
            field=models.DecimalField(decimal_places=15, help_text="Contractor's GPS longitude when uploading photo", max_digits=20),
        ),
    ]
